
CURRENT_REFERENCE_GAGE = '07030500'
CURRENT_HUC_ID = '08010210'
CURRENT_START_YEAR = "2006"
CURRENT_END_YEAR = "2007"
CURRENT_START_DATE = f"{CURRENT_START_YEAR}-10-01"
CURRENT_END_DATE = f"{CURRENT_END_YEAR}-10-01"
CURRENT_OUTLET_YX = (21,0)
CURRENT_RUN_NAME = "WOLF"

DOMAIN_NAME = f"WOLF_{CURRENT_START_YEAR}_to_{CURRENT_END_YEAR}"
# This is the grid cell pumping rate if we pumped from every grid cell. 
# Divide by the fraction of grid cells for this domain that are irrigated to 
# get the adjusted pumping rate.
TENESSEE_DOMAIN_PUMPED_AREA_FRACTION = 0.4807826694619147
TENESSEE_DOMAIN_GRID_CELL_PUMPING_RATE = 6.51497175976849e-07
UNIT_PUMPING_RATE = TENESSEE_DOMAIN_GRID_CELL_PUMPING_RATE * TENESSEE_DOMAIN_PUMPED_AREA_FRACTION


P = 4
Q = 4