
DRY_YEAR = 2006
AVERAGE_YEAR = 2007
CURRENT_START_YEAR = DRY_YEAR

CURRENT_REFERENCE_GAGE = '07030500'
CURRENT_HUC_ID = '08010210'
CURRENT_END_YEAR = CURRENT_START_YEAR + 1
CURRENT_START_DATE = f"{CURRENT_START_YEAR}-10-01"
CURRENT_END_DATE = f"{CURRENT_END_YEAR}-10-01"
CURRENT_OUTLET_YX = (32,0)
CURRENT_RUN_NAME = "WOLF"



DOMAIN_NAME = f"WOLF_{CURRENT_START_YEAR}_to_{CURRENT_END_YEAR}"
# This is the grid cell pumping rate if we pumped from every grid cell. 
# Divide by the fraction of grid cells for this domain that are irrigated to 
# get the adjusted pumping rate.
VIRGINIA_CONSUMPTIVE_USE_MGAL_PER_DAY = 16.03
VIRGINA_CONSUMPTIVE_USE_M3_PER_DAY = 4404.8838 * VIRGINIA_CONSUMPTIVE_USE_MGAL_PER_DAY
VIRGINIA_AREA_KM2 = 110785.67
GRID_CELL_AREA_KM2 = 1.0

GRID_CELL_CONSUMPTIVE_USE_M3_PER_DAY = VIRGINA_CONSUMPTIVE_USE_M3_PER_DAY / VIRGINIA_AREA_KM2 * GRID_CELL_AREA_KM2
GRID_CELL_AREA_M2 = GRID_CELL_AREA_KM2 * 1000000.0 # convert to m2
GRID_CELL_CONSUMPTIVE_USE_M_PER_DAY = GRID_CELL_CONSUMPTIVE_USE_M3_PER_DAY/GRID_CELL_AREA_M2 # convert to m3/m2/day
GRID_CELL_CONSUMPTIVE_USE_M_PER_HOUR = GRID_CELL_CONSUMPTIVE_USE_M_PER_DAY / 24.0

# For now use 1 inch per week because that is a number a lot of crops need
GRID_CELL_CONSUMPTIVE_USE_M_PER_HOUR = 0.00015119
P = 4
Q = 4